/*
 * =========================================================================================
 * STRICT SECURITY POLICY:
 * NO ONE CAN EVER CHANGE THE ORGANIZATION TYPE FROM THE FRONTEND OR BACKEND.
 * NEVER ADD A DROPDOWN OR OPTION TO CHANGE IT ANYWHERE IN THE CODEBASE.
 * NO MEANS NO. THIS IS A FIXED PLATFORM RULE.
 * =========================================================================================
 */

/**
 * billingErrorCodes.js
 * Standardized error codes for frontend-backend contract.
 */

export const BILLING_ERRORS = {
    // Validation Errors
    INVALID_CURRENCY: "INVALID_CURRENCY",
    INVALID_AMOUNT: "INVALID_AMOUNT",
    NON_INTEGER_PAISE: "NON_INTEGER_PAISE",
    MISSING_TAX_RULE: "MISSING_TAX_RULE",

    // State Errors
    INVOICE_ALREADY_PAID: "INVOICE_ALREADY_PAID",
    INVOICE_IMMUTABLE: "INVOICE_IMMUTABLE", // Cannot modify after ISSUED
    SUBSCRIPTION_NOT_ACTIVE: "SUBSCRIPTION_NOT_ACTIVE",
    PLAN_RETIRED: "PLAN_RETIRED",

    // Payment Errors
    PAYMENT_FAILED: "PAYMENT_FAILED",
    SIGNATURE_MISMATCH: "SIGNATURE_MISMATCH",
    DUPLICATE_WEBHOOK: "DUPLICATE_WEBHOOK",
    ORDER_CREATION_FAILED: "ORDER_CREATION_FAILED",
    REFUND_FAILED: "REFUND_FAILED",

    // Concurrency Errors
    CONCURRENT_MODIFICATION: "CONCURRENT_MODIFICATION",
    IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT"
};
