import dotenv from 'dotenv';
dotenv.config();

import { sendEmail } from './src/services/aws-ses.service.js';
import { baseTemplate } from './src/services/email-templates.service.js';

const content = `
    <img src="https://cdn.classgrid.in/Happy_diwali_2026.png" style="width: 100%; border-radius: 8px; margin-bottom: 24px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);" alt="Happy Diwali 2026" />

    <h2 style="color: #111111; margin-top: 0; margin-bottom: 16px;">Hi Nikhil,</h2>
    
    <p style="color: #374151; font-size: 14px; line-height: 1.7; margin-bottom: 20px;">As the festive season brings light and new beginnings, we wanted to take a moment to wish you and your family a very Happy and Prosperous Diwali!</p>
    
    <p style="color: #374151; font-size: 14px; line-height: 1.7; margin-bottom: 20px;">We know the semester is incredibly busy, so we hope you get a chance to take a break, enjoy the celebrations, and spend quality time with the people who matter most.</p>
    
    <div style="background-color: #f9f9f9; border: 1px solid #eaeaea; border-radius: 8px; padding: 20px; margin-bottom: 24px;">
      <p style="color: #374151; font-size: 14px; line-height: 1.7; margin-bottom: 0;">At <strong style="color: #111111;">Classgrid</strong>, we are building the next generation of software to make college life and campus management easier for students and faculty alike. As an initiative born right here at PCCOE, your continued support means the world to us.</p>
    </div>
    
    <p style="color: #374151; font-size: 14px; line-height: 1.7; margin-bottom: 24px;">May this festival of lights bring you success, joy, and a lot of great code! 🚀</p>
    
    <p style="color: #374151; font-size: 14px; line-height: 1.7; margin-bottom: 24px;">Warm regards,<br>
    <strong style="color: #111111;">The Classgrid Team</strong><br>
    <a href="https://www.classgrid.in" style="color: #111111;">www.classgrid.in</a></p>
`;

const htmlTemplate = baseTemplate({
  content: content,
  title: "Happy Diwali from Classgrid",
  ignoreText: "This email was automatically generated by the Classgrid Ecosystem."
});

async function test() {
  try {
    // Send to QuantumChem
    await sendEmail({
      to: 'quantumchem25@gmail.com',
      subject: 'Wishing you a very Happy Diwali, Nikhil! 🪔✨',
      html: htmlTemplate,
      text: 'Wishing you a very Happy Diwali from Classgrid!',
      fromName: 'The Classgrid Team',
      fromEmail: 'diwali@classgrid.in'
    });
    console.log("TEST SUCCESSFUL - Sent to quantumchem25@gmail.com");

    process.exit(0);
  } catch (err) {
    console.error("TEST FAILED", err);
    process.exit(1);
  }
}

test();
